### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by stared** [MarekCichy/StaredTasks#2]
- [x] `nsfw_df = pd.read_csv('nsfw.csv', index_col='image')`
- [x] `plt.hist(nsfw_df['Nude Detect'], bins = 10)` -> `nsfw_df['Nude Detect'].hist(bins=10)`
- [x] zrobić pętlą, po nazwach, a nie ręcznie wszytskie (hint: `nsfw_df.columns` i `plt.title(name)` oraz `plt.show()`)
- [x] prócz `sns.heatmap` polecam `sns.clustermap`
- [x] w sumie można też zobaczyć na porównania korelację spearmana i petersona

Co do taska z liniami to jedna część OK, cała reszta od czapy (co przestawiają? nie mam pojęcia).

Stąd polecam coś w stylu (prócz tego 5-stopniowego)

```
for name in df.columns:
  nsfw_df[name].sort_values().plot()
```

**Comment by stared** [comment]
Histograms

- [ ] `bins=10` not `bins = 10`, for fcks sake!
- [ ] `range=(0, 1)`

Line plots comparing all

- [ ] drop this 1-5 scale, or rescale it ot 0.2-1.0
- [ ] For this sorted plot, use legends

Pairs

- [ ] For comparing classifiers pairs, use 2d scatter plots (not sorted line)
- [ ] Try as well https://seaborn.pydata.org/generated/seaborn.pairplot.html

**Comment by MarekCichy** [comment]
Cześć, nie rozumiem tylko range = (0,1) ? W jakim celu?

**Comment by stared** [comment]
Bez. Spacji. W. Argumentach. Funkcji.

W celu, że jak domyślnie historgram się tworzy od min do max, to może
być nie co 10%, ale np od 4.2% do 91%, wtedy przedziały będą inne.

Piotr

**Comment by MarekCichy** [comment]
już już! już nie ma spacji! ;)
nie wrzuciłem byłem dzisiejszych poprawek na github(tych przy których odznaczylem Twoje issues) :/

**Comment by MarekCichy** [comment]
All issues adressed (afaik)
@stared anything more you would deem interesting to perform on these data?

**Comment by stared** [comment]
Fajnie! 

Teraz już tylko trzeba pomyśleć jak to dobrze spisać. :)
